# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "testvm" do |cfg|
    cfg.vm.box = "generic/alpine318"
    cfg.vm.hostname = "testvm"
    cfg.vm.network "private_network", ip: "10.1.245.33"

    cfg.vm.provider "libvirt" do |v|
      v.driver = "kvm"
      v.memory = 1024
      v.cpus = 2
    end
  end
end


